/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  safelist: [{ pattern: /^(bg|text|border)-cat-([1-9]|1[0-9]|2[0-4])-(bg|fg)$/ }],
  theme: {
    extend: {
      colors: {
        bg: "rgb(var(--bg-rgb) / <alpha-value>)",
        surface: {
          DEFAULT: "rgb(var(--surface-rgb) / <alpha-value>)",
          alt: "rgb(var(--surface-alt-rgb) / <alpha-value>)",
          sunken: "rgb(var(--surface-sunken-rgb) / <alpha-value>)",
        },
        border: {
          DEFAULT: "rgb(var(--border-rgb) / <alpha-value>)",
          strong: "rgb(var(--border-strong-rgb) / <alpha-value>)",
        },
        text: {
          primary: "color-mix(in srgb, var(--text-primary) calc(<alpha-value> * 100%), transparent)",
          secondary: "color-mix(in srgb, var(--text-secondary) calc(<alpha-value> * 100%), transparent)",
          disabled: "color-mix(in srgb, var(--text-disabled) calc(<alpha-value> * 100%), transparent)",
        },
        primary: {
          DEFAULT: "color-mix(in srgb, var(--primary) calc(<alpha-value> * 100%), transparent)",
          hover: "color-mix(in srgb, var(--primary-hover) calc(<alpha-value> * 100%), transparent)",
          active: "color-mix(in srgb, var(--primary-active) calc(<alpha-value> * 100%), transparent)",
          soft: "color-mix(in srgb, var(--primary-soft) calc(<alpha-value> * 100%), transparent)",
          ghost: "color-mix(in srgb, var(--primary-ghost) calc(<alpha-value> * 100%), transparent)",
          fg: "color-mix(in srgb, var(--on-primary) calc(<alpha-value> * 100%), transparent)",
        },
        income: {
          DEFAULT: "color-mix(in srgb, var(--income) calc(<alpha-value> * 100%), transparent)",
          soft: "color-mix(in srgb, var(--income-soft) calc(<alpha-value> * 100%), transparent)",
        },
        expense: {
          DEFAULT: "color-mix(in srgb, var(--expense) calc(<alpha-value> * 100%), transparent)",
          soft: "color-mix(in srgb, var(--expense-soft) calc(<alpha-value> * 100%), transparent)",
        },
        warning: {
          DEFAULT: "color-mix(in srgb, var(--warning) calc(<alpha-value> * 100%), transparent)",
          soft: "color-mix(in srgb, var(--warning-soft) calc(<alpha-value> * 100%), transparent)",
        },
        error: {
          DEFAULT: "color-mix(in srgb, var(--error) calc(<alpha-value> * 100%), transparent)",
          soft: "color-mix(in srgb, var(--error-soft) calc(<alpha-value> * 100%), transparent)",
        },
        info: {
          DEFAULT: "color-mix(in srgb, var(--info) calc(<alpha-value> * 100%), transparent)",
        },
        cat: {
          "1-bg": "color-mix(in srgb, var(--cat-1-bg) calc(<alpha-value> * 100%), transparent)",
          "1-fg": "color-mix(in srgb, var(--cat-1-fg) calc(<alpha-value> * 100%), transparent)",
          "2-bg": "color-mix(in srgb, var(--cat-2-bg) calc(<alpha-value> * 100%), transparent)",
          "2-fg": "color-mix(in srgb, var(--cat-2-fg) calc(<alpha-value> * 100%), transparent)",
          "3-bg": "color-mix(in srgb, var(--cat-3-bg) calc(<alpha-value> * 100%), transparent)",
          "3-fg": "color-mix(in srgb, var(--cat-3-fg) calc(<alpha-value> * 100%), transparent)",
          "4-bg": "color-mix(in srgb, var(--cat-4-bg) calc(<alpha-value> * 100%), transparent)",
          "4-fg": "color-mix(in srgb, var(--cat-4-fg) calc(<alpha-value> * 100%), transparent)",
          "5-bg": "color-mix(in srgb, var(--cat-5-bg) calc(<alpha-value> * 100%), transparent)",
          "5-fg": "color-mix(in srgb, var(--cat-5-fg) calc(<alpha-value> * 100%), transparent)",
          "6-bg": "color-mix(in srgb, var(--cat-6-bg) calc(<alpha-value> * 100%), transparent)",
          "6-fg": "color-mix(in srgb, var(--cat-6-fg) calc(<alpha-value> * 100%), transparent)",
          "7-bg": "color-mix(in srgb, var(--cat-7-bg) calc(<alpha-value> * 100%), transparent)",
          "7-fg": "color-mix(in srgb, var(--cat-7-fg) calc(<alpha-value> * 100%), transparent)",
          "8-bg": "color-mix(in srgb, var(--cat-8-bg) calc(<alpha-value> * 100%), transparent)",
          "8-fg": "color-mix(in srgb, var(--cat-8-fg) calc(<alpha-value> * 100%), transparent)",
          "9-bg": "color-mix(in srgb, var(--cat-9-bg) calc(<alpha-value> * 100%), transparent)",
          "9-fg": "color-mix(in srgb, var(--cat-9-fg) calc(<alpha-value> * 100%), transparent)",
          "10-bg": "color-mix(in srgb, var(--cat-10-bg) calc(<alpha-value> * 100%), transparent)",
          "10-fg": "color-mix(in srgb, var(--cat-10-fg) calc(<alpha-value> * 100%), transparent)",
          "11-bg": "color-mix(in srgb, var(--cat-11-bg) calc(<alpha-value> * 100%), transparent)",
          "11-fg": "color-mix(in srgb, var(--cat-11-fg) calc(<alpha-value> * 100%), transparent)",
          "12-bg": "color-mix(in srgb, var(--cat-12-bg) calc(<alpha-value> * 100%), transparent)",
          "12-fg": "color-mix(in srgb, var(--cat-12-fg) calc(<alpha-value> * 100%), transparent)",
          "13-bg": "color-mix(in srgb, var(--cat-13-bg) calc(<alpha-value> * 100%), transparent)",
          "13-fg": "color-mix(in srgb, var(--cat-13-fg) calc(<alpha-value> * 100%), transparent)",
          "14-bg": "color-mix(in srgb, var(--cat-14-bg) calc(<alpha-value> * 100%), transparent)",
          "14-fg": "color-mix(in srgb, var(--cat-14-fg) calc(<alpha-value> * 100%), transparent)",
          "15-bg": "color-mix(in srgb, var(--cat-15-bg) calc(<alpha-value> * 100%), transparent)",
          "15-fg": "color-mix(in srgb, var(--cat-15-fg) calc(<alpha-value> * 100%), transparent)",
          "16-bg": "color-mix(in srgb, var(--cat-16-bg) calc(<alpha-value> * 100%), transparent)",
          "16-fg": "color-mix(in srgb, var(--cat-16-fg) calc(<alpha-value> * 100%), transparent)",
          "17-bg": "color-mix(in srgb, var(--cat-17-bg) calc(<alpha-value> * 100%), transparent)",
          "17-fg": "color-mix(in srgb, var(--cat-17-fg) calc(<alpha-value> * 100%), transparent)",
          "18-bg": "color-mix(in srgb, var(--cat-18-bg) calc(<alpha-value> * 100%), transparent)",
          "18-fg": "color-mix(in srgb, var(--cat-18-fg) calc(<alpha-value> * 100%), transparent)",
          "19-bg": "color-mix(in srgb, var(--cat-19-bg) calc(<alpha-value> * 100%), transparent)",
          "19-fg": "color-mix(in srgb, var(--cat-19-fg) calc(<alpha-value> * 100%), transparent)",
          "20-bg": "color-mix(in srgb, var(--cat-20-bg) calc(<alpha-value> * 100%), transparent)",
          "20-fg": "color-mix(in srgb, var(--cat-20-fg) calc(<alpha-value> * 100%), transparent)",
          "21-bg": "color-mix(in srgb, var(--cat-21-bg) calc(<alpha-value> * 100%), transparent)",
          "21-fg": "color-mix(in srgb, var(--cat-21-fg) calc(<alpha-value> * 100%), transparent)",
          "22-bg": "color-mix(in srgb, var(--cat-22-bg) calc(<alpha-value> * 100%), transparent)",
          "22-fg": "color-mix(in srgb, var(--cat-22-fg) calc(<alpha-value> * 100%), transparent)",
          "23-bg": "color-mix(in srgb, var(--cat-23-bg) calc(<alpha-value> * 100%), transparent)",
          "23-fg": "color-mix(in srgb, var(--cat-23-fg) calc(<alpha-value> * 100%), transparent)",
          "24-bg": "color-mix(in srgb, var(--cat-24-bg) calc(<alpha-value> * 100%), transparent)",
          "24-fg": "color-mix(in srgb, var(--cat-24-fg) calc(<alpha-value> * 100%), transparent)",
        },
      },
      borderRadius: {
        chip: "8px",
        tile: "10px",
        ctl: "12px",
        card: "16px",
        panel: "20px",
        modal: "28px",
      },
      height: {
        "ctl-sm": "36px",
        ctl: "44px",
        "ctl-lg": "52px",
      },
      minHeight: {
        "ctl-sm": "36px",
        ctl: "44px",
        "ctl-lg": "52px",
      },
      boxShadow: {
        sh1: "var(--sh1)",
        sh2: "var(--sh2)",
        sh3: "var(--sh3)",
      },
      fontSize: {
        "display-xl": ["30px", { lineHeight: "1.15", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg": ["20px", { lineHeight: "1.25", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-md": ["16px", { lineHeight: "1.3", fontWeight: "700" }],
        "num-xl": ["28px", { lineHeight: "1.1", fontWeight: "800" }],
        "num-lg": ["20px", { lineHeight: "1.2", fontWeight: "700" }],
        num: ["14px", { lineHeight: "1.4", fontWeight: "700" }],
        body: ["14px", { lineHeight: "1.55", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
        label: ["12px", { lineHeight: "1.4", fontWeight: "600" }],
        caption: ["11px", { lineHeight: "1.4", fontWeight: "500" }],
        overline: ["11px", { lineHeight: "1.2", letterSpacing: "0.06em", fontWeight: "600" }],
      },
      fontFamily: {
        display: ["Manrope", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};


